repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 --config setup.cfg .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort --settings-file setup.cfg . -c
        language: system
        types: [ python ]
        pass_filenames: false
