version: '3.3'
volumes:
  pg_data:
  static_data:
  media_data:

services:

  db:
    image: ${DB_IMAGE}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME}/foodgram_backend
    env_file:
      - ./.env
    volumes:
      - media_data:/app/foodgram/media/
      - static_data:/app/static/
    restart: always
    depends_on:
      gateway:
        condition: service_started

  frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend
    volumes:
      - static_data:/static
    command: cp -r /app/build/. /static/
    depends_on:
      db:
        condition: service_healthy

  gateway:
    image: ${DOCKER_USERNAME}/foodgram_gateway
    volumes:
      - static_data:/usr/share/nginx/html/
      - media_data:/usr/share/nginx/html/media/
    restart: always
    ports:
      - 9001:80
    depends_on:
      frontend:
        condition: service_completed_successfully
