version: '3.3'
volumes:
  pg_data:
  static_data:
  media_data:

services:

  db:
    image: ${DB_IMAGE}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      db:
        condition: service_started

  gateway:
    image: ${GATEWAY_VERSION}
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_data:/var/html/media/
      - static_data:/var/html/static/
    restart: always
    depends_on:
      frontend:
        condition: service_completed_successfully

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - GUNICORN_VERSION=${GUNICORN_VERSION}
    env_file: ../backend/.env
    volumes:
      - media_data:/app/foodgram/media/
      - static_data:/app/staticfiles/
    restart: always
    depends_on:
      gateway:
        condition: service_started
