version: '3.3'

volumes:

  pg_data:
  static_data:
  media_data:

services:

  db:
    image: ${DB_IMAGE}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend/
      dockerfile: Dockerfile
      args:
        - PYTHON_VERSION=${PYTHON_VERSION}
        - GUNICORN_VERSION=${GUNICORN_VERSION}
    env_file: ../backend/.env
    volumes:
      - media_data:/app/foodgram/media/
      - static_data:/app/backend_static/
    command: sh -c "python manage.py collectstatic -c --noinput && cp -r /app/staticfiles/. /app/backend_static/ && gunicorn --bind 0.0.0.0:8000 config.wsgi"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      backend:
        condition: service_started

  gateway:
    image: ${GATEWAY_VERSION}
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - media_data:/usr/share/nginx/html/media/
      - static_data:/usr/share/nginx/html/static_backend/
    restart: unless-stopped
    depends_on:
      frontend:
        condition: service_completed_successfully
